### ISSUE TITLE
The Unity version in package.json is incorrect

### ISSUE THREAD

**Issue by RoBit666** [ToshikiImagawa/Scrmizu#16]
The error occurs if installed as a package. You must specify a version in a different format.
Error text:
```
An error occurred while resolving packages:
  Folder [<PROJECT_PATH>\Packages] contains invalid packages:
    Manifest [<PROJECT_PATH>\Packages\Scrmizu\package.json] is invalid:
      '2020.3.45f1' is not a valid `unity` property value. Expected '<year>.<version>'.
```

**Comment by ToshikiImagawa** [comment]
Thank you for notifying us! The issue has been resolved with the[ v1.1.6 version](https://github.com/ToshikiImagawa/Scrmizu/releases/tag/v1.1.6). If you encounter any further problems, feel free to reach out. Happy coding!
