### ISSUE TITLE
 namespace name 'IInfiniteScrollItem' could not be found

### ISSUE THREAD

**Issue by UmarHyatt-programmer** [ToshikiImagawa/Scrmizu#4]
Assets\Scrmizu.Sample\Scripts\Runtime\HorizontalScrollItem.cs(11,56): error CS0246: The type or namespace name 'IInfiniteScrollItem' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ToshikiImagawa** [comment]
Thank you for reporting.

**Comment by ToshikiImagawa** [comment]
@UmarHyatt-programmer

Is Scrmizu included in the Inspector Field > Assembly Definition References ?
Also, have you changed the namespace of SampleApp?
If so, you will need to using Scrmizu.

---

Inspector Field > Assembly Definition References に、Scrmizu は含まれていますでしょうか？
また、SampleAppの 名前空間を変更していませんでしょうか？
変更している場合、Scrmizuをインポートする必要があります。
